# Replace the text below to customize your site
site_name: Seher Krishna - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Seher Krishna
copyright: Copyleft 2021 "Seher Krishna" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:

  - About: about/me.md
  - Master project:
      - Final: project/project.md
      - Design Studio: project/studio.md
  - Reflections :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          - BioZero: term1/03-BioZero.md
          - DesignStudio: term1/04-DesignStudio.md
          - Livingwithyourownideas: term1/05-Living with your own ideas.md
          - Techbeyondthemyth: term1/06-Tech Beyond the Myth.md
          - CommunityEngagement: term1/07-Community Engagement.md
          - ExtendedIntelligences: term1/08-Extended Intelligences.md


      - Term 2:
          - NextBillionSeconds: term2/01-Billion Seconds.md
          - RemixingMaterials: term2/02-Remixing Materials.md
          - MakingSense&Meaning: term2/03-Making Sense & Meaning.md
          - DigitalPrototyping: term2/04-Digital Prototyping for Design.md
          - CommunicatingIdeas: term2/05-Communicating Ideas.md
          - MeasuringtheWorld: term2/06-Measuring the World.md
          - FutureTalks: term2/07-Future Talks.md

      - Term 3:
          - DistributedDesign: term3/01-Distributed Design.md
          - ProtoypingforDesign: term3/02-Microchallenge.md
          - DesignEthics: term3/03-Design Ethics.md
          - HumanInterfaces: term3/04-Human Interfaces.md
          - DAO: term3/05-Decentralised Autonomous Organisation.md
          - TransfeministDesign: term3/06-Transfeminist Design.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/seherkrishna/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SeherKrishna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seher-krishna-4209a4190/
    - icon: fontawesome/brands/github
      link: https://seherkrishna02.github.io/mdef4/

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: blue
  font:
    # See available fonts at https://fonts.google.com/
    text: Space Mono
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
